### ISSUE TITLE
`GLIBC_2.34' not found error with linux exes from latest release

### ISSUE THREAD

**Issue by aleaf** [MODFLOW-USGS/executables#34]
Hi all, when trying to run the latest mf6 and mp7 linux exes on Cent OS 7, I'm getting the following error:
```
mf6: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by mf6)
mp7: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by mp7)
```
Not sure if it's relevant, but this machine has gfortran 4.8.5

Let me know if you need any other details, and thanks in advance for looking at this!

@wpbonelli , @jdhughes-usgs

**Comment by wpbonelli** [comment]
@aleaf I don't think we can make any guarantees about the linux build's compatibility with alternative (non-ubuntu) distros.. my understanding is you can generally get a binary built on ubuntu to run on centos, provided you install and point it to all the right library versions, but it might be easier just to compile on that machine. I think you'll need a newer gfortran, though.

**Comment by jdhughes-usgs** [comment]
@aleaf I suspect the executables would work if you installed gfortran 11 to 13 but I am not sure you will be able to get new compiler versions on CentOS. I suspect you would be able to build mp7 with gfortran 4.8.5 but not mf6.

**Comment by mwtoews** [comment]
If older versions are OK, then download [version 9.0](https://github.com/MODFLOW-USGS/executables/releases/tag/9.0) which should work with older Linux versions.

But for newer releases, there isn't an easy solution (here are some in this [Q/A](https://serverfault.com/questions/894625/safely-upgrade-glibc-on-centos-7)), except to recompile the tools that you need from the source files on the host system.

Generally, portable Linux executables need to be compiled on old Linux versions, since newer versions have backwards compatibility with older glibc versions. A good resource is [HBB](https://github.com/phusion/holy-build-box); see an example build for [pestpp here](https://github.com/usgs/pestpp/tree/master/scripts). Binary Python tools use a similar approach with [manylinux](https://github.com/pypa/manylinux), where "pip install" for binary packages like numpy works across most distros.

**Comment by aleaf** [comment]
Thanks guys. Follow-up question- CentOS 7 is clearly out of date, but the rest of our machines are using Rocky 8.10, which was just released this last may. The glibc version for that is 2.28, so it seems that we would have to compile locally to get MODFLOW to work on those. Is there any way to support somewhat older glibc versions?

**Comment by aleaf** [comment]
This worked for the Rocky 8.10 machines:

- Download the [GCC Toolset](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/developing_c_and_cpp_applications_in_rhel_8/additional-toolsets-for-development_developing-applications#uninstalling-gcc-toolset_gcc-toolset) version 12 with `dnf install gcc-toolset-12`
- enable this in a bash session (`scl enable gcc-toolset-12 bash`); means that `gfortran` will call version 12 instead of the system version)
- activate the `modflow6` conda environment and build MODFLOW 6 using meson, following the [instructions on the MODFLOW 6 GitHub page](https://github.com/MODFLOW-USGS/modflow6/blob/develop/DEVELOPER.md)
