### ISSUE TITLE
MF6 6.3 much much slower than 6.1.1?

### ISSUE THREAD

**Issue by Neilt100** [MODFLOW-USGS/executables#5]
I'm not quite sure where to raise this issue- I have an mf6 model that was originally developed using mf6 version 6.1.1.  It is steady state and has 1 stress period (10950 days) and 6 time steps (1825 days each).  With Mf6 version 6.1.1 it takes around 16 seconds to run, whereas with version 6.3 it now takes 33 seconds to run.  There is no difference between the input files or the laptop I'm using to run the model (on the C: drive).

Just wondering where the overhead comes from in v 6.3?  The extra time isn't a big deal (apart from using it in PEST)- it was originally a mf-nwt model converted to mf6 (using the converter executable).  I converted it because it originally ran much faster in Mf6 (v 6.1.1).  I now need to use the GWT functionality, hence the update to v 6.3.

Thanks for your help.

**Comment by langevin-usgs** [comment]
Hey @Neilt100, I'd be curious to know why the model is slower with 6.3.  There have been lots of changes since 6.1.1.  Have you looked through the 6.3 release notes (both for the 6.3 changes and those listed in the appendix)?  Maybe you can spot a change that would affect your model.   It might be as simple as adjusting an input parameter.  We also track a comparison of run times here: https://modflow6.readthedocs.io/en/latest/_mf6run/run-time-comparison.html.

If you can't get to the bottom of it, I'd be happy to take a look of you can get me a copy of your model.

I'm going to close this issue here, but please feel free to add information or reopen.  And if we find something that is clearly a problem, then we should probably open an issue on the modflow6 GitHub site.
